#!/bin/bash

. ./functions-lib

readConfig

messageId=$1
mark=$2
mark=`echo "${mark}" | awk '{print tolower($0)}'`
locoID=$3
startDate=$4
startTime=$5
endDate=$6
endTime=$7

log "AMTK started"
log "Message ID = $messageId, mark = $mark"

manifest=/tmp/${messageId}.manifest
packageId=${mark}.${locoID}.${messageId}

pathstring=${AMTK_DIR}/amtk.l.${mark}.${locoID}:mdm/
log "Path string is ${pathstring}"

sendStatus "${messageId}" "$RESPONSE_STATUS_QUEUE" 1 None

foundFiles=/tmp/sort.${messageId}.all
sudo find "${pathstring}" -type f -name "*.log.gz" | egrep -v "install|depart_test|fault_history|event_history" | sort --key 7 --field-separator=. >${foundFiles}
log "Number of normal log files found by find: `wc -l $foundFiles`"

filterLogs ${startDate} ${endDate} ${startTime} ${endTime} ${manifest} ${foundFiles}

sudo find "${pathstring}" -type f -name "*.log.gz" | grep "fault_history" | sort --key 6 --field-separator=. >${foundFiles}
log "Number of fault_history logs found by find: `wc -l $foundFiles`"

filterLogs ${startDate} ${endDate} ${startTime} ${endTime} ${manifest} ${foundFiles}

sudo find "${pathstring}" -type f -name "*.log.gz" | grep "depart_test" | sort --key 5 --field-separator=. >${foundFiles}
log "Number of depart_test logs found by find: `wc -l $foundFiles`"

filterLogs ${startDate} ${endDate} ${startTime} ${endTime} ${manifest} ${foundFiles}

sudo find "${pathstring}" -type f -name "*.log.gz" | grep "event_history" | sort --key 6 --field-separator=. >${foundFiles}
log "Number of event_history logs found by find: `wc -l $foundFiles`"

filterLogs ${startDate} ${endDate} ${startTime} ${endTime} ${manifest} ${foundFiles}

putLogsToS3 ${manifest} ${messageId} ${packageId}

log "AMTK worker completed request $messageId"