#!/bin/bash

. ./functions-lib
. ./strof-lib

readConfig

# shellcheck disable=SC2034
messageId=$1
federations_list=$2

FEDCHECK="/usr/bin/python fed-check"

# shellcheck disable=SC2001
for federation in $(echo "$federations_list" | sed "s/,/ /g")
do
    log "Running check for federation $federation"

    servers_statuses=$(mktemp)
    $FEDCHECK "$federation" > "$servers_statuses"

    log "FEDCHECK output:"
    cat "$servers_statuses"

    servers=$(wc -l < "$servers_statuses")

    if [ "$servers" -eq 0 ]; then
          sendStatus "${messageId}" "$RESPONSE_FEDERATION_QUEUE" "3000" "$federation;0;0"
    else
          # shellcheck disable=SC2002
          # shellcheck disable=SC2126
          operational=$(cat "$servers_statuses" | grep Operational | wc -l)
          sendStatus "${messageId}" "$RESPONSE_FEDERATION_QUEUE" "3000" "$federation;$servers;$operational"
    fi
done

sendStatus "${messageId}" "$RESPONSE_FEDERATION_QUEUE" "3001"
