#!/bin/bash

. ./functions-lib

readConfig

messageId=$1
mark=$2
locoID=$3
startDate=$4
startTime=$5
endDate=$6
endTime=$7

log "VREX started"
log "Message ID = $messageId"

manifest=/tmp/${messageId}.manifest
packageId=${mark}.${locoID}.${messageId}

pathstring=${VREX_DIR}/${mark}${locoID}/
log "Path string is $pathstring"

sendStatus $messageId 1 None

foundFiles=/tmp/sort.${messageId}.all
sudo find "${pathstring}" -type f -name "*.log.gz" | egrep -v "depart_test|fault_history|event_history|failure_history" | sort --key 4 --field-separator=. >${foundFiles}
log "Number of normal files found by find: `wc -l $foundFiles`"

filterLogs ${startDate} ${endDate} ${startTime} ${endTime} ${manifest} ${foundFiles}

sudo find "${pathstring}" -type f -name "*.log.gz" | grep "fault_history" | sort --key 3 --field-separator=. >${foundFiles}
log "Number of fault_history files found by find: `wc -l $foundFiles`"

filterLogs ${startDate} ${endDate} ${startTime} ${endTime} ${manifest} ${foundFiles}

sudo find "${pathstring}" -type f -name "*.log.gz" | grep "depart_test" | sort --key 2 --field-separator=. >${foundFiles}
log "Number of depart_test files found by find: `wc -l $foundFiles`"

filterLogs ${startDate} ${endDate} ${startTime} ${endTime} ${manifest} ${foundFiles}

sudo find "${pathstring}" -type f -name "*.log.gz" | grep "event_history" | sort --key 3 --field-separator=. >${foundFiles}
log "Number of event_history files found by find: `wc -l $foundFiles`"

filterLogs ${startDate} ${endDate} ${startTime} ${endTime} ${manifest} ${foundFiles}

sudo find "${pathstring}" -type f -name "*.log.gz" | grep "failure_history" | sort --key 3 --field-separator=. >${foundFiles}
log "Number of failure_history files found by find: `wc -l $foundFiles`"

filterLogs ${startDate} ${endDate} ${startTime} ${endTime} ${manifest} ${foundFiles}

putLogsToS3 ${manifest} ${messageId} ${packageId}
log "VREX worker completed request $messageId"