#!/bin/bash

. ./functions-lib

POLL_TIMEOUT=5

readConfig

while :
do
        log "STROF: Next polling loop"

        message=$(receiveMessage "$INCOMING_FEDERATION_QUEUE")

        if [[ -z "$message" ]]; then
                log "No new messages"
                sleep $POLL_TIMEOUT
                continue
        fi

        messageId=$(echo "$message" | jq -r '.Messages[0].MessageId')
        receiptHandle=$(echo "$message" | jq -r '.Messages[0].ReceiptHandle')
        federations=$(echo "$message" | jq -r '.Messages[0].MessageAttributes.federations.StringValue')

        log "Getting status of federations: $federations"

        jobsCount=$(jobs -r | wc -l)
        log "Number of running jobs = $jobsCount"

        if [[ "$jobsCount" -gt "$MAX_JOBS" ]]; then
                log "Maximum number of workers exceeded, waiting..."
                sleep $POLL_TIMEOUT
                continue
        fi

        log "Starting a worker"
        workers/FEDERATION "$messageId" "$federations" &
        log "Deleting the incoming message"
        deleteMessage "$receiptHandle" "$INCOMING_FEDERATION_QUEUE"

        sleep $POLL_TIMEOUT
done